### ISSUE TITLE
Admin UI times out with large amount of tags

### ISSUE THREAD

**Issue by benmay** [coffee2code/custom-post-limits#2]
Hi! Very valuable plugin, but we work on sites that can have anywhere from 20,000 - 100,000 tags - and your plugin times out where you do a `get_tags()` call.

Happy to put a pull request together to fix this. I would say the easiest way to do this would be a filter that we could define on our sites so that tag pages are all the same, and remove ability to select specific tags. 

We've hacked the plugin to check and we were able to get it to work, wanted to check with you first before supplying a patch/pull request.

**Comment by coffee2code** [comment]
Hi Ben!

Thanks for the report! I can see where this is an issue and is something I overlooked when attempting to address this problem in the past. For the performance reasons you've experienced, the plugin was changed awhile ago to actually disable individual tag/author/category limits by default. A checkbox (and a filter) were added to enable individual tag/author/category support.

_However_, I neglected the fact that it was still actually getting the list of all tags even though it wasn't using them.

Here's a diff of the change I quickly tested that seems like it should properly prevent `get_tags()` from being called (unless explicitly enabled to do so via the filter or setting).

The diff relates to the plugin's function named `get_tags()`, which is the last method defined for the class and the last function defined in the file (`custom-post-limits.php`):

```
-                       $this->tags = get_tags( array( 'hide_empty' => false ) );
+                       $this->tags = $this->is_individual_limits_enabled( 'tags' )
+                               ? get_tags( array( 'hide_empty' => false ) )
+                               : true;
```

If that's something you can easily test and confirm it works for you, that'd be great. If it works, I'll make a similar change for `get_authors()` and `get_categories()`, as well as a few other trivial plugin updates, and push out an update in short order.

**Comment by benmay** [comment]
I will test this tomorrow and report back!

**Comment by coffee2code** [comment]
476003e incorporates the changes I alluded to in my previous comment, along with unit tests. Let me know if that doesn't resolve your issue.

(A new release of the plugin hasn't been made yet, though.)

Thanks again for the report!

**Comment by benmay** [comment]
Thanks for fixing!
