### ISSUE TITLE
Dynamic Pagination

### ISSUE THREAD

**Issue by benmay** [coffee2code/custom-post-limits#3]
Hey! Another question -- have you had much luck making this plugin compatible with any richer pagination code? The issue is that on Page 1, the max pages is miscalculated.

EG:

on /category/trucks/
Pagination may say Page 1 of 209

Then on /category/trucks/page/2/ 
Pagination will say Page 1 of 100

We've had to code this up manually for another project, but would love to contribute to make the pagination work correctly. 

The reason we don't just do Next / Prev pages is because we want to have shallower crawl depth on older archive pages. The overall goal with using this plugin is to reduce number of paged results on older archive pages (10,000's of posts)

**Comment by coffee2code** [comment]
I wasn't aware of any issues with pagination, but I see what you're getting at.

I've started work on addressing the problem and have it just about all worked out. I'll follow up shortly with the commit that should fix this.

**Comment by benmay** [comment]
Yeh it'll be an interesting one to resolve.

The way we've resolved it now, is on page 1 we just have a "Next Page" Link,

Here is how we solve it now;
```
if ( is_paged() ) {

	the_posts_pagination(array(

		'prev_text' => __( 'Newer Posts', 'textdomain' ),

		'next_text' => __( 'Older Posts', 'textdomain' ),

	));

} else {

	next_posts_link( __( 'Older Posts' ) );

	previous_posts_link( __( 'Newer Posts' ) );

}
```
